# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bliss' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bliss

  pod 'LZViewPager'
  pod 'Shuffle-iOS'
  pod 'MessageKit'
  pod 'RSSelectionMenu'
  
  target 'BlissTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BlissUITests' do
    # Pods for testing
  end

end
